# Generated by Django 5.2.8 on 2025-11-11 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('biomass_above_a', models.FloatField(blank=True, null=True)),
                ('biomass_above_b', models.FloatField(blank=True, null=True)),
                ('root_ratio', models.FloatField(blank=True, help_text='Relación raíz/aérea', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_class', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=3)),
                ('distance_in_row_m', models.FloatField(default=0)),
                ('distance_between_rows_m', models.FloatField(default=0)),
                ('radius_m', models.FloatField(default=0, help_text='Radio de parcela, si aplica')),
                ('age_years', models.PositiveIntegerField(default=0)),
                ('dominant_height_m', models.FloatField(default=0)),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciefap.producer')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciefap.species')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('dap_cm', models.FloatField()),
                ('height_m', models.FloatField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='ciefap.plot')),
            ],
        ),
    ]
